spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/graphql_demo
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  graphql:
    graphiql:
      enabled: true
  threads:
    virtual:
      enabled: true

server:
  port: 8081