spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/graphql_demo
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  graphql:
    graphiql:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    operationsSorter: method
    display-request-duration: true

server:
  port: 8081